name: Makefile CI

on:
  push:
    branches: [ "heroltexx-user-8.0.0-R16NW-G930FXXS8ETC1-release-keys" ]
  pull_request:
    branches: [ "heroltexx-user-8.0.0-R16NW-G930FXXS8ETC1-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    -name: Run install
     run: make install

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.1
        release_name: Release v1.0.0
        body: |
          Release notes for v1.0.0

          initial release     
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./herolte.zip
        asset_name: herolte.zip
        asset_content_type: application/zip
